### ISSUE TITLE
[Feature]KernelSU support

### ISSUE THREAD

**Issue by jeffpeng3** [jjyao88/unlock-felica-pixel#1]
請問有沒有打算porting到kernelSU上
即使使用了magisk delta+shamiko等等也仍會被不少軟體偵測出來
實測只有kernelSU可以最大程度防偵測
且pixel的root使用者有一部分也因為不用自己編譯kernel而使用kernelSU了

我有試著自己porting了
但礙於dynamic installer只支援magisk而毫無頭緒

**Comment by jjyao88** [comment]
Hi @jeffpeng3,
目前我的環境是 Magisk Alpha + Shamiko，是能夠躲過國泰、郵局、富邦的 Root 檢測。
我這個月再找個時間試試看改寫成兼容 KernelSU 的模組。

**Comment by jjyao88** [comment]
順便調查一下，請問你目前使用的 Pixel 型號以及運行的 Android 系統版本是多少。
 
如果改成如我前面所說的使用 Magisk Alpha 環境刷入的話，Google 錢包有改成新介面嗎？以及Osaifu-Keitai 是否能正常使用。

再拜託您了，謝謝！

**Comment by jeffpeng3** [comment]
pixel 8 pro不能裝
android14
應該是因為只支援純64bit導致的

![Screenshot_20231019-122346.png](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/fb4d3cc6-0ff6-4065-974a-19ceeaf7e818)

![Screenshot_20231019-122546.png](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/446608e0-3d67-461b-9a93-472c3f5006a6)

**Comment by jeffpeng3** [comment]
pixel 4 xl正常
pixysOS android13

![Screenshot_20231019-142911.png](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/02a7a83d-a6b8-4867-aa09-b0ce3ff3f850)

![Screenshot_20231019-142932.png](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/f9e17561-5920-4246-9192-bf34537944fb)

**Comment by jjyao88** [comment]
@jeffpeng3 哈囉，謝謝你的測試！

2.0 版本更換成 MMT-Extended 的架構，應該是可以安裝在 KernelSU 上面了
如果安裝在 Pixel 8 Pro / Pixel 4 XL 的過程當中遇到問題的話，再麻煩把安裝日誌（右上角存檔按鈕）傳過來這邊！

謝謝

**Comment by jeffpeng3** [comment]
pixel 8 pro
android 14
magisk delta
安裝失敗
[magisk_install_log_2023-10-20T03.16.17.log](https://github.com/jjyao88/unlock-felica-pixel/files/13046833/magisk_install_log_2023-10-20T03.16.17.log)




pixel 4 xl
android 13
kernelSU
刪除卡片重裝確定正常

![image](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/cb9bf2d0-2aee-4fa7-9ed6-9fcda132b867)

**Comment by jjyao88** [comment]
> pixel 8 pro
> android 14
> magisk delta
> 安裝失敗
> [magisk_install_log_2023-10-20T03.16.17.log](https://github.com/jjyao88/unlock-felica-pixel/files/13046833/magisk_install_log_2023-10-20T03.16.17.log)
> 
> 
> 
> 
> pixel 4 xl
> android 13
> kernelSU
> 刪除卡片重裝確定正常


看起來是因為 aapt 沒有辦法正常執行，不太確定是不是運行 Android 14 的關係，Pixel 4 XL 到目前還沒有 A14 的 Custom ROM 出現，所以我也不方便測試，我再試試看更新 aapt 跟 apktool 好了

**Comment by jeffpeng3** [comment]
我可以幫忙檢查版本
如果有.sh可以快速的檢查可用性之類的
姑且會一點shell使用
---
坐捷運順手clone下來小測了一下
看來確實是因為32bit不能執行
我用termux裝的是64bit可以正常執行
![Screenshot_20231020-100308.png](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/b64128a7-7049-4b7e-bb64-62cf94960ba1)

**Comment by jjyao88** [comment]
@jeffpeng3 
我剛更新了一版，把使用到的 binaries 更新至 aarch64 版本，應該可以在 Android 14 使用了。
再請你幫我測試一下，謝謝！

**Comment by jeffpeng3** [comment]
V2.1版pixel 8 pro可以正常安裝了
google錢包介面也變了
但是
直到我剛剛想新增卡片的時候才發現
我無法初始化osaifu-keitai app
![image](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/5739dd70-b780-42f9-9a17-2780c813b628)

回頭看了pixel 4 xl
發現原來V2.0的時候
pixel 4 xl上osaifu-keitai app也不能開了
只是當初已經初始化過了
所以可以正常刪除新增卡片

我也稍微確認了一下
兩台手機的felica/common.cfg應該都如預期了
![image](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/d22647f8-c392-46ac-aa24-268fbb960230)

如果還需要什麼有關的log我都可以提供

**Comment by jjyao88** [comment]
> V2.1版pixel 8 pro可以正常安裝了 google錢包介面也變了 但是 直到我剛剛想新增卡片的時候才發現 我無法初始化osaifu-keitai app ![image](https://user-images.githubusercontent.com/54392299/276890784-5739dd70-b780-42f9-9a17-2780c813b628.png)
> 
> 回頭看了pixel 4 xl 發現原來V2.0的時候 pixel 4 xl上osaifu-keitai app也不能開了 只是當初已經初始化過了 所以可以正常刪除新增卡片
> 
> 我也稍微確認了一下 兩台手機的felica/common.cfg應該都如預期了 ![image](https://user-images.githubusercontent.com/54392299/276892771-d22647f8-c392-46ac-aa24-268fbb960230.png)
> 
> 如果還需要什麼有關的log我都可以提供

你好！兩者的安裝日誌貼到這邊我研究一下
PS: 我確認一下 Pixel 4L 你是用 KernelSU 環境安裝對吧！？

**Comment by jeffpeng3** [comment]
pixel 8 pro
magisk delta
V2.1
等到確定正常之後
會再刷上今天剛release的kernelSU再驗證一次
[magisk_install_log_2023-10-20T17.57.35.log](https://github.com/jjyao88/unlock-felica-pixel/files/13053004/magisk_install_log_2023-10-20T17.57.35.log)
---- --- -
pixel 4 xl
kernelSU
V2.0(因為這一版就出問題了)
[KernelSU_install_log_2023-10-20-17-58-25.log](https://github.com/jjyao88/unlock-felica-pixel/files/13053005/KernelSU_install_log_2023-10-20-17-58-25.log)

**Comment by jjyao88** [comment]
> pixel 8 pro magisk delta V2.1 等到確定正常之後 會再刷上今天剛release的kernelSU再驗證一次 [magisk_install_log_2023-10-20T17.57.35.log](https://github.com/jjyao88/unlock-felica-pixel/files/13053004/magisk_install_log_2023-10-20T17.57.35.log)
> 
> pixel 4 xl kernelSU V2.0(因為這一版就出問題了) [KernelSU_install_log_2023-10-20-17-58-25.log](https://github.com/jjyao88/unlock-felica-pixel/files/13053005/KernelSU_install_log_2023-10-20-17-58-25.log)

我剛剛測試了 KernelSU ，應該是 Shamiko 的關係，你要先把幫 Osaifu-keitai 掛上 Root 授權，然後把它的資料清除，接著重啟就可以正常使用。

另外從日誌上看起來 Pixel 8 Pro 安裝過程正常，v2.1.1 我有手動設置 apk 和 `felica/common.cfg` 的權限試試看能不能解決。
更新後同樣地先把 Osaifu-keitai 的資料清空，再試試看還能不能使用。

**Comment by jeffpeng3** [comment]
pixel 4 xl確定正常了

pixel 8 pro則是換了一個錯誤
![image](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/7d2fdabb-2dad-438f-b728-edd8596a43c6)

**Comment by jjyao88** [comment]
> pixel 8 pro則是換了一個錯誤 !

第一次看到這種錯誤欸...
你安裝的 [Osaifu-Keitai](https://play.google.com/store/apps/details?id=com.felicanetworks.mfm.main) 是 33.23.15 最新版嗎？
（順便檢查一下 [Osaifu-Keitai Setting Application](https://play.google.com/store/apps/details?id=com.felicanetworks.mfs)，畫面的字串來自這邊）
如果是最新版的話，再告訴我一下這個錯誤是到哪個流程後出現的

**Comment by jeffpeng3** [comment]
版本最新
![image](https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/212ea607-b127-4432-9f3c-12e1ba257886)
過程如下
就是初始化完就顯示了
https://github.com/jjyao88/unlock-felica-pixel/assets/54392299/efa26db9-8665-4893-91f8-368ed7b3b0f0

**Comment by jjyao88** [comment]
@jeffpeng3 
你試試看如果把 Adguard 之類的VPN服務關掉呢？
我檢查了一下原始碼，~~錯誤似乎跟網路有關（BaseMfiEventCallback.TYPE_HTTP_COMMUNICATION_ERROR）~~

**Comment by jeffpeng3** [comment]
magisk給權限了
adguard也直接解除安裝了
問題依舊
但願不是pixel 8 pro還沒解鎖這功能

**Comment by jjyao88** [comment]
KernelSU is fully supported in version 2.0+.
