### ISSUE TITLE
Charge card.

### ISSUE THREAD

**Issue by Hungermanw3t** [jjyao88/unlock-felica-pixel#11]
How do I add money to the mobile suica. Both suica app and Google pay don't work.

**Comment by jjyao88** [comment]
Please try to use another credit card (e.g. better with Mastercard or JCB) and charge your Suica card again.
Few IC card companies in Japan are known for blocking some credit card issuers outside Japan

**Comment by Hungermanw3t** [comment]
I have an Australian issued Mastercard that wouldn't work through Google wallet or suica app. It did work however by charging it with cash through a kiosk. Now it's charged, it works really well. You can add pixel 7 to the list of working devices too.

**Comment by jjyao88** [comment]
That's unfortunate, I get a Taiwan-issued JCB card and can charge my ICOCA and Suica cards without problems.
At least you can still recharge your card with the cash at a kiosk!
Anyway, thanks for your sharing :)
