### ISSUE TITLE
v2.2 works partially with Pixel 7a (lynx)

### ISSUE THREAD

**Issue by marcus65001** [jjyao88/unlock-felica-pixel#12]
Android Version: 14
Magisk 27000
Play Integrity API: MEETS_BASIC

Installed v2.2 at first and the Osaifu-Keitai fails with the following error: `This app contains configuration files for services in Japan and has no menu items`. But it seems like Osaifu-Keitai can be initialized properly through Google Wallet and I am able to add Suica.

Tried v2.1.1 later and both apps worked.

Your work on this is truly appreciated, thank you.

**Comment by jjyao88** [comment]
Could it be related to #9?

For v2.2, it seems that Osaifu-Keitai app doesn't read the proper configuration file, try to remove `com.google.pixelnfc` from the Magisk denylist.

However, it's glad to see v2.1.1 is still working like a charm.

Thank you for letting me know this information.
