### ISSUE TITLE
Set up successfully but no response when tapping

### ISSUE THREAD

**Issue by kirosc** [jjyao88/unlock-felica-pixel#13]
Hi, first of all, thank you for writing this mod.

I can install the module and set up three Osaifu Keitai apps successfully. However, when I tap my phone at the station's readers, there's no response. I can use Google wallet to pay with credit card without problem.

Device: Pixel 8 latest version
Environment: KernelSu
Module I installed: 
- Pixelify
- Play Integrity Fix
- systemless hosts
- Shamiko, Zygisk - Sui
- Zygisk Next

**Comment by jjyao88** [comment]
Hi, what kind of FeliCa card do you use?

In order to tap and pay at the station, remember to download the traffic IC card into your phone (for example, Suica, ICOCA or PASMO) first.

**Comment by kirosc** [comment]
Thanks for the reply. I disabled several modules and it works. Will report later to see which one is conflicting

**Comment by kirosc** [comment]
Turn out it's the [NFC card emulator](https://play.google.com/store/apps/details?id=com.yuanwofei.cardemulator.pro)'s module causing the trouble.

**Comment by jjyao88** [comment]
Thanks for your report!
I have updated the FAQ regarding this situation.
