### ISSUE TITLE
SUList needs Osaifu-Keitai [com.felicanetworks.mfm.main] added in order to work

### ISSUE THREAD

**Issue by babyhuehnchen** [jjyao88/unlock-felica-pixel#14]
If you are using a SUList system rather than a denylist system (in my case Kitsune Delta), it is required to specifically add Osaifu-Keitai to the SUList or else you will get a generic error when trying to generate a Card in Google Wallet. Would be useful to have this on the guide as I initially thought the Android March Update broke the module until i read the info about KernelSU, attempted to add Osaifu-Keitai to SUList and it started working right away

**Comment by jjyao88** [comment]
Good to see you figured it out and thanks for your report!
I have updated the FAQ in the repo.
