### ISSUE TITLE
unroot and retain IC cards in Google Wallet?

### ISSUE THREAD

**Issue by a-woo** [jjyao88/unlock-felica-pixel#15]
After installing this and adding Pasmo/SUICA card to Google Wallet, can I safely unroot my device and lock the bootloader again while retaining access to the IC cards in Google Wallet?

**Comment by jjyao88** [comment]
Hi,
As you have downloaded IC cards into your device, it's okay for you to unroot the device.
The drawback is after unrooting you may no longer open Osaifu-keitai app to manage your cards. The only way to do it is just through the Google Wallet.
