### ISSUE TITLE
这个怎么使用呢？

### ISSUE THREAD

**Issue by drakett007** [jjyao88/unlock-felica-pixel#17]
是吧文件解压到手机里就可以使用么？
可以讲解一下么？
可否增加apk版本，这样方便实用呢？
我用的是小米14pro

這個怎麼使用呢？
是把文件解壓到手機的某個文件夾麼？
可以講解一下麼？
可以增加apk版本安裝麼？
我用的是小米14pro 有成功解鎖的用戶麼？
謝謝

**Comment by jjyao88** [comment]
小米 14 Pro 硬體本身並沒有內建 Felica 元件，所以是沒辦法用上這個模組的。
目前僅有日本國內銷售的手機，以及 Google Pixel 國際版與日版才有。

**Comment by kaedea** [comment]
> 小米 14 Pro 硬體本身並沒有內建 Felica 元件，所以是沒辦法用上這個模組的。
> 目前僅有日本國內銷售的手機，以及 Google Pixel 國際版與日版才有。

是否可以认为目前只有 Pixel 设备才有这种“硬件支持 Felica 但是软件上不启用支持”的情况？因为我看到 Xiaomi Japan 在售的设备都是标明不支持 Felica，不确定是否用类似的方案来开启支持。

**Comment by jjyao88** [comment]
> 是否可以认为目前只有 Pixel 设备才有这种“硬件支持 Felica 但是软件上不启用支持”的情况？因为我看到 Xiaomi Japan 在售的设备都是标明不支持 Felica，不确定是否用类似的方案来开启支持。

是的，全球發售的 Pixel 裝置皆內建 Felica 元件，差異在於除了日本以外全部裝置都上了軟體鎖，得靠 Root 的方案來解鎖
