### ISSUE TITLE
Pixel 9 Pro XL is working now

### ISSUE THREAD

**Issue by KoukeNeko** [jjyao88/unlock-felica-pixel#18]
![Screenshot_20240823-001225](https://github.com/user-attachments/assets/6b613f28-8ab7-4673-882e-76670da71d91)
![Screenshot_20240823-001238](https://github.com/user-attachments/assets/904721b0-9a31-4216-92da-a6982dea837c)
![image](https://github.com/user-attachments/assets/aecef2a7-a765-4238-b992-dbca91f65e36)
![image](https://github.com/user-attachments/assets/460d1214-aa5b-422e-b680-5fd9ec9fea9b)

**Comment by jjyao88** [comment]
Thank you for the report! I hope you enjoy your new phone. :)
