### ISSUE TITLE
Add Pixel 9 Pro Fold to devices list

### ISSUE THREAD

**Issue by xaliax** [jjyao88/unlock-felica-pixel#19]
I was sucessfull installing this to a Pixel 9 Pro Fold (android 14)

![Screenshot_20240912-091656](https://github.com/user-attachments/assets/e30d7b03-c2af-4a91-91e5-38c7b4e02e67)

**Comment by jjyao88** [comment]
Thanks for your report 😃

**Comment by xaliax** [comment]
It is also working for Android 15. Updated a few days ago and I am currently using it while traveling in Japan! Thanks for creating this! 💪

**Comment by jjyao88** [comment]
> It is also working for Android 15. Updated a few days ago and I am currently using it while traveling in Japan! Thanks for creating this! 💪

Glad to hear that! I hope you enjoy the trip there :)
