### ISSUE TITLE
Can you support android 15 🙏? 

### ISSUE THREAD

**Issue by HuixingWong** [jjyao88/unlock-felica-pixel#21]
Seems not work on android 15

**Comment by jiatern** [comment]
I changed from `MAXAPI=34` to `MAXAPI=35` in customize.sh and it works on my Pixel 8 Pro with Android 15.

If you trust me you can use the file below, or just edit yourself

[unlock-felica-pixel-A15.zip](https://github.com/user-attachments/files/17279066/unlock-felica-pixel-A15.zip)

**Comment by HuixingWong** [comment]
> I changed from `MAXAPI=34` to `MAXAPI=35` in customize.sh and it works on my Pixel 8 Pro with Android 15.
> 
> If you trust me you can use the file below, or just edit yourself
> 
> [unlock-felica-pixel-A15.zip](https://github.com/user-attachments/files/17279066/unlock-felica-pixel-A15.zip)

Thank u very much !

**Comment by jjyao88** [comment]
Hi, sorry for the late reply.
I'm awaiting the stable release of Android 15 for Pixels on 10/15.
Since @jiatern has managed make my module compatible by merely adjusting the `MAXAPI` setting, I believe it's okay to release a quick fix.

**Comment by jjyao88** [comment]
I have released [v2.3](https://github.com/jjyao88/unlock-felica-pixel/releases/tag/v2.3) which introduces A15 support.
If you encounter any issue, please let me know :)

Thank you!

**Comment by jiatern** [comment]
@jjyao88 Just flashed, it's working perfectly :) By the way I forgot to install com.felicanetworks.mfs and it's still working fine, so I guess I'll leave it as-is.

**Comment by jjyao88** [comment]
> @jjyao88 Just flashed, it's working perfectly :) By the way I forgot to install com.felicanetworks.mfs and it's still working fine, so I guess I'll leave it as-is.

@jiatern  `com.felicanetworks.mfs` is required only for the first time configurating Felica component on your phone.
After that, feel free to uninstall it. Even if you do a clean flash, there's no need to reinstall it again.
