### ISSUE TITLE
Question about unrooting

### ISSUE THREAD

**Issue by adokitkat** [jjyao88/unlock-felica-pixel#23]
Hi! Thanks for your work. I just wanted to ask if I were to root my Pixel phone, unlock Felica and then unroot it and lock bootloader again, would it then passed Safety net again and could I still use banking apps and such? Thanks for answer.

**Comment by jjyao88** [comment]
Hi, I believe it would receive a strong verdict from Play Integrity after flashing back to stock ROM and re-locking the bootloader.

Your Felica IC cards may continue to be used through Google Wallet, but they cannot be managed via Osaifu-Keitai.
