### ISSUE TITLE
v2.2 works great on Pixel 8 Pro、Pixel 7 Pro

### ISSUE THREAD

**Issue by jce12356** [jjyao88/unlock-felica-pixel#4]
Hi, I just installed your module on Pixel 8/7 Pro which version is 2.2. I comfirmed v2.2 is working on these devices without problems.
You can add these two models to README.md
May I share your amazing work to Facebook group named "[Google Pixel 手機同樂會（Taiwan）](https://www.facebook.com/groups/381562282386976/)"?

**Comment by jjyao88** [comment]
Thanks for sharing :)
It's welcome to share my repo in the Facebook group

**Comment by kormax** [comment]
Thanks for reporting!

@jjyao88,
So if I understand correctly, it was the simultaneous presence of `00000014` and `00000015` with `00000018` that caused the issue?  If yes, great that it was solved!
BTW, I've linked this repo in my tutorial. Great job you and @starks.

**Comment by jjyao88** [comment]
> Thanks for reporting!
> 
> @jjyao88, So if I understand correctly, it was the simultaneous presence of `00000014` and `00000015` with `00000018` that caused the issue? If yes, great that it was solved! BTW, I've linked this repo in my tutorial. Great job you and @starks.

Since OP only tested with v2.2 version, I'm still not sure it is the reason that failed during initial setup.

However, it looks like patching `felica/common.cfg` could only be universal solution for unlocking Felica.

**Comment by jce12356** [comment]
Quick update
V2.2 also working on my Pixel 6 Pro (Android 13 with Magisk 26302 not Delta)

**Comment by jjyao88** [comment]
> Quick update V2.2 also working on my Pixel 6 Pro (Android 13 with Magisk 26302 not Delta)

much appreciate!
