### ISSUE TITLE
G Wallet reset?

### ISSUE THREAD

**Issue by Hungermanw3t** [jjyao88/unlock-felica-pixel#6]
Does installing this module require any form of reset to google wallet or play services?

**Comment by jjyao88** [comment]
> Does installing this module require any form of reset to google wallet or play services?

There is no need to reset your google wallet data.
Just flash the module and reboot, and then give it some time for google wallet to update the information. the new UI will show up eventually.

**Comment by Hungermanw3t** [comment]
That's great. I've been having lots of fun resetting g wallet because of play protect and it was getting a bit annoying.

**Comment by Hungermanw3t** [comment]
Reopened to ask if the google play services for payments app is required?

**Comment by Hungermanw3t** [comment]
Also, how do I install the other apps. They all say I'm in the wrong region.

**Comment by jjyao88** [comment]
> Reopened to ask if the google play services for payments app is required?

It's required.

> Also, how do I install the other apps. They all say I'm in the wrong region.

Create a Japanese Google account and install them on Play Store or just download them from APKPure.

**Comment by Hungermanw3t** [comment]
I've downloaded everything and it all looks good. Thank you for your help. I won't be able to test it in the field for a few months but in theory I've finished the setup process for pixel 7 on android 14.
