### ISSUE TITLE
Doesnt work on my phone

### ISSUE THREAD

**Issue by hungyip** [jjyao88/unlock-felica-pixel#7]
Pixel 8. Installed the module, and then installed the com.felicanetworks.mfm.main

Using a Japan VPN, it is still giving me the "This app contain configuration files for services in Japan and has no menu items" error
I am using Magisk Delta and not sure if it is the cause.

Tried both 2.2 and 2.1

**Comment by jjyao88** [comment]
Hi!
Could you provide me with the installation log and which version of Magisk Delta do you use?

**Comment by hungyip** [comment]
我可以講中文。

我的 Pixel 7 跟 8 pro 都不行。我拍了一個 screen video。影片中我沒有 reboot 只是想把 Osaifu-Keitei
的 error 也拍出來，實際上我已經 reboot 過幾次了。

https://youtube.com/shorts/fA3Bx10ghks?si=gBc5AZwvfLdo24zi

Raymond

**Comment by jjyao88** [comment]
> 我可以講中文。 我的 Pixel 7 跟 8 pro 都不行。我拍了一個 screen video。影片中我沒有 reboot 只是想把 Osaifu-Keitei 的 error 也拍出來，實際上我已經 reboot 過幾次了。 

詢問一下你目前的 Magisk Delta 設置，你是不是有在設定打開 Unmount modules 的功能？
因為如果你有為 Osaifu-Keitei 相關的 Apps 開啟這功能的話，那些 Apps 會沒有辦法讀取到修改後的設定檔。

**Comment by hungyip** [comment]
這個嗎，這個有勾，但 mount list 沒選 osaifu keitei

**Comment by hungyip** [comment]
我把新装的 4 個 app 都勾了，現在可以進去了，但到 setup 就 failed.

**Comment by jjyao88** [comment]
你遇到的問題是跟[這部影片](https://github-production-user-asset-6210df.s3.amazonaws.com/54392299/276967049-efa26db9-8665-4893-91f8-368ed7b3b0f0.mp4)一樣嗎？

是的話再幫我確認一下你是不是安裝 v2.2 的版本

**Comment by hungyip** [comment]
是的，一模一樣，我是裝了 2.2

**Comment by hungyip** [comment]
是否要插上日本的 sim 才 okay?

**Comment by jjyao88** [comment]
> 是否要插上日本的 sim 才 okay?

抱歉由於近日比較忙，比較晚回覆您。
不需要日本sim卡也可以解鎖，另外能否再請您嘗試看看 Magisk Alpha / KernelSU 的方式，因為前兩者都有人初次解鎖成功過。

另外 Google 近日嚴抓繞過  Play Integrity 的方式，若無定時檢查安裝[新的補丁](https://github.com/chiteroman/PlayIntegrityFix)來修正的話，裝置很容易沒通過 DEVIVE Verdict。目前還不確定這個因素是否會影響每台裝置能否**成功初次解鎖**，但目前 Google Pay 至少要有 DEVICE verdict 才能夠接觸付款支付。

P.S. 你可以安裝[這個 App](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck)檢查裝置是否通過 Play Integrity。

**Comment by hungyip** [comment]
Play integrity 我是有 pass 的。我都有用 wallet 信用卡。你意思是試一下不要用 delta 用其他 magisk 嗎？

Raymond

**Comment by jjyao88** [comment]
> Play integrity 我是有 pass 的。我都有用 wallet 信用卡。你意思是試一下不要用 delta 用其他 magisk 嗎？ 

是的

**Comment by jjyao88** [comment]
@hungyip 
哈囉！
根據 #9 的回報，他原本也是跟你有相同的問題，但是他從 Magisk Denylist 把 `com.google.pixelnfc` 拿掉後，就可以通過初始化。
再請你確認看看是不是有把  `com.google.pixelnfc` 加入到 denylist 中，有的話再拿掉重試看看。

**Comment by hungyip** [comment]
我看了我手機裡面沒有 com.google.pixelnfc

我試試不用 delta
