### ISSUE TITLE
Reversal process?

### ISSUE THREAD

**Issue by Hungermanw3t** [jjyao88/unlock-felica-pixel#8]
What is the best way to reverse the changes. Preferably without loosing the suica card/balance.

**Comment by jjyao88** [comment]
If you plan to use the same Suica card on the same device in the future.
Download the suica card to your device first and uninstall the module and related apps.

Or if you plan to use it on a different device, upload Suica card to the cloud from Osaifu-Keitai app first, and then uninstall the module.
