### ISSUE TITLE
Neither v2.2 nor v2.1.1 working on Pixel 8 Pro

### ISSUE THREAD

**Issue by negimeister** [jjyao88/unlock-felica-pixel#9]
I can't get mobile Suica to work on my Pixel 8 Pro purchased in Switzerland.
These are the steps I took:
- Unlocked bootloader and rooted phone with Magisk patched init_boot.img
- Enable Zygisk
- Hide Magisk and add basically every app on the phone to the Denylist
- Install the Play Integrity Fix module by chiteroman
- Verified I have MEETS_BASIC_INTEGRITY and MEETS_DEVICE_INTEGRITY in Play Store (i.e. SafetyNet passes)
- Install Wallet and the three Osaifu Keitai apps (com.felicanetworks.mfm.main, com.felicanetworks.mfc, com.felicanetworks.mfs)
- Install either v2.2 or v2.1 of this module
- Enable Japanese VPN
- Try to set up Suica in Google Wallet

That's where the issue shows. It asks me to "complete phone setup" which opens the Osaifu Keitai settings, it prompts me to start setup, shows a short loading screen saying "Connecting to mobile network" and then errors out with "Not available on this phone"

Google Wallet works otherwise, I successfully added my credit card to it. And the menu item for adding JP e-Money shows up after the mod, so I'm lost as to what's missing.

**Comment by negimeister** [comment]
Nevermind, I found the issue. I had com.google.pixelnfc on the Magisk denylist. That broke all the unlock methods.

**Comment by jjyao88** [comment]
Glad to hear that and thanks for your report! 
There is one guy that encounters the same issue as you. I'm making sure if he does put `com.google.pixelnfc` into the Magisk denylist. If he can manage to pass the initialization during the setup by removing it from the list and I'll update my README.

Update: By the way, did you install version 2.1.1 of the module to pass the setup then?

**Comment by negimeister** [comment]
I did have 2.1.1 installed last, but also an LSPosed module that modifies the pixelnfc app. The denylist broke both 2.1.1 and 2.2, so I assume both would work without it.

**Comment by Originalimoc** [comment]
Interesting. I use 2.1.1 and didn't even have Enforce DenyList enabled because hide root/superuser is done by Shamiko but if com.google.pixelnfc is on the denylist it also won't work. How can it be?
